//------------------------------------------------------------------------------
// File       : CSR_in_agent_xaction_pkg.sv
// Author     : automatically generated by picker integration
// Date       : 2026-02-03
// Description: Package wrapper for Picker-generated Python-UVM agent
//------------------------------------------------------------------------------

package CSR_in_agent_xaction_pkg;
  import utils_pkg::*;
  import uvm_pkg::*;
  import uvmc_pkg::*;
  import CSR_in_agent_pkg::*;
  
  `include "xagent.sv"
endpackage