# File       : __init__.py
# Author     : automatically generated by picker
# Date       : 2026-02-03 12:11:13
# Description: Python package initialization for CSR_in_agent_xaction
# Version    : v0.1

"""
CSR_in_agent_xaction Python Package

UVM transaction-based communication package.
"""

__version__ = "v0.1"

# ============================================================================
# Common imports for both DUT and Agent modes
# ============================================================================
try:
    from . import tlm_pbsb as u
    from . import xspcomm as xsp
    from .xagent import Agent, BaseTransaction, CSR_in_agent_xaction
except ImportError as e:
    import sys
    print(f"Error: Failed to import required modules: {e}", file=sys.stderr)
    print("Make sure tlm_pbsb, xspcomm, and xagent modules are properly installed.", file=sys.stderr)
    raise

# ============================================================================
# DUT Mode: Integrated __init__.py with DUT implementation
# ============================================================================

from typing import Optional, Callable, Dict, Type, List
import struct
import os
import sys
import subprocess

# ============================================================================
# Unified Initialization: Path handling + LD_PRELOAD
# ============================================================================

# VCS Mode: Auto LD_PRELOAD handling
dut_dir = os.path.dirname(os.path.abspath(__file__))
so_path = os.path.join(dut_dir, '_tlm_pbsb.so')

# Convert paths to absolute (always do this)
def _to_abs(arg):
    if arg.startswith('-'):
        return arg
    if '::' in arg:
        path, test = arg.split('::', 1)
        return f"{os.path.abspath(path)}::{test}" if os.path.exists(path) else arg
    return os.path.abspath(arg) if os.path.exists(arg) else arg

new_args = [_to_abs(arg) for arg in sys.argv]

# Handle LD_PRELOAD and directory switching
if '_LD_PRELOAD_HANDLED' not in os.environ and os.environ.get('SKIP_LD_PRELOAD') != '1':
    if os.path.exists(so_path):
        # Setup environment
        env = os.environ.copy()
        env['LD_PRELOAD'] = f"{so_path}:{env.get('LD_PRELOAD', '')}" if env.get('LD_PRELOAD') else so_path
        env['_LD_PRELOAD_HANDLED'] = '1'
        env['PYTHONPATH'] = os.path.dirname(dut_dir)
        
        # Run in DUT directory if needed
        if os.path.abspath(os.getcwd()) != dut_dir:
            is_pytest = 'pytest' in sys.modules or 'PYTEST_CURRENT_TEST' in os.environ
            result = subprocess.run(
                [sys.executable] + new_args, env=env, cwd=dut_dir,
                capture_output=is_pytest, text=is_pytest
            )
            
            if is_pytest:
                print(result.stdout, end='')
                print(result.stderr, end='', file=sys.stderr)
                # Handle VCS crash but tests passed
                if result.returncode < 0 and ' passed' in (result.stdout + result.stderr):
                    os._exit(0)
            
            os._exit(result.returncode if result.returncode >= 0 else 1)
        else:
            os.execve(sys.executable, [sys.executable] + new_args, env)



# ==================== DUT Implementation ====================

class _PinWrapper:
    """Wrapper to provide dut.pin.value access instead of dut.pin.xdata.value"""
    def __init__(self, xpin: xsp.XPin):
        self._xpin = xpin

    @property
    def value(self):
        return self._xpin.xdata.value

    @value.setter
    def value(self, val):
        self._xpin.xdata.value = val

    @property
    def xpin(self):
        return self._xpin

    @property
    def xdata(self):
        return self._xpin.xdata

    @property
    def event(self):
        return self._xpin.event  

class DUTCSR_in_agent_xaction:
    """
    DUT abstraction for CSR_in_agent_xaction with pin-level interface.

    Pins:
    - io_csr_intrBitSet: 1-bit signal
    - io_csr_wfiEvent: 1-bit signal
    - io_csr_criticalErrorState: 1-bit signal
    - io_snpt_snptDeq: 1-bit signal
    - io_snpt_useSnpt: 1-bit signal
    - io_snpt_snptSelect: 2-bit signal
    - io_snpt_flushVec_0: 1-bit signal
    - io_snpt_flushVec_1: 1-bit signal
    - io_snpt_flushVec_2: 1-bit signal
    - io_snpt_flushVec_3: 1-bit signal
    - io_wfi_safeFromMem: 1-bit signal
    - io_wfi_safeFromFrontend: 1-bit signal
    - io_wfi_enable: 1-bit signal
    - io_fromVecExcpMod_busy: 1-bit signal
    - io_readGPAMemData_gpaddr: 56-bit signal
    - io_readGPAMemData_isForVSnonLeafPTE: 1-bit signal
    - io_vstartIsZero: 1-bit signal
    - io_debugEnqLsq_canAccept: 1-bit signal
    - io_debugEnqLsq_needAlloc_0: 2-bit signal
    - io_debugEnqLsq_needAlloc_1: 2-bit signal
    - io_debugEnqLsq_needAlloc_2: 2-bit signal
    - io_debugEnqLsq_needAlloc_3: 2-bit signal
    - io_debugEnqLsq_needAlloc_4: 2-bit signal
    - io_debugEnqLsq_needAlloc_5: 2-bit signal
    - io_debugEnqLsq_req_0_valid: 1-bit signal
    - io_debugEnqLsq_req_0_bits_robIdx_value: 8-bit signal
    - io_debugEnqLsq_req_0_bits_lqIdx_value: 7-bit signal
    - io_debugEnqLsq_req_1_valid: 1-bit signal
    - io_debugEnqLsq_req_1_bits_robIdx_value: 8-bit signal
    - io_debugEnqLsq_req_1_bits_lqIdx_value: 7-bit signal
    - io_debugEnqLsq_req_2_valid: 1-bit signal
    - io_debugEnqLsq_req_2_bits_robIdx_value: 8-bit signal
    - io_debugEnqLsq_req_2_bits_lqIdx_value: 7-bit signal
    - io_debugEnqLsq_req_3_valid: 1-bit signal
    - io_debugEnqLsq_req_3_bits_robIdx_value: 8-bit signal
    - io_debugEnqLsq_req_3_bits_lqIdx_value: 7-bit signal
    - io_debugEnqLsq_req_4_valid: 1-bit signal
    - io_debugEnqLsq_req_4_bits_robIdx_value: 8-bit signal
    - io_debugEnqLsq_req_4_bits_lqIdx_value: 7-bit signal
    - io_debugEnqLsq_req_5_valid: 1-bit signal
    - io_debugEnqLsq_req_5_bits_robIdx_value: 8-bit signal
    - io_debugEnqLsq_req_5_bits_lqIdx_value: 7-bit signal
    - io_debugInstrAddrTransType_bare: 1-bit signal
    - io_debugInstrAddrTransType_sv39: 1-bit signal
    - io_debugInstrAddrTransType_sv39x4: 1-bit signal
    - io_debugInstrAddrTransType_sv48: 1-bit signal
    - io_debugInstrAddrTransType_sv48x4: 1-bit signal
    - io_storeDebugInfo_0_robidx_value: 8-bit signal
    - io_storeDebugInfo_1_robidx_value: 8-bit signal
    - compare: 1-bit signal
    - CSR_in_agent_xaction: 1-bit signal
    - super_result: 1-bit signal
    Example:
        >>> dut = DUTCSR_in_agent_xaction()

        >>> dut.io_csr_wfiEvent.value = 10

        >>> dut.Step(1)
    """

    def __init__(self, **kwargs):
        """Initialize DUT with Agent and xspcomm infrastructure."""
        self._event = xsp.Event()
        self._xports: Dict[str, xsp.XPort] = {}
        self._user_callback: Optional[Callable[['DUTCSR_in_agent_xaction'], None]] = None
        self._xpins = {}
        self._callback_pending = False

        # Monitor feedback extra cycles (configurable)
        self._monitor_extra_cycles: int = kwargs.get('monitor_extra_cycles', 1)

        # Initialize XPins and XPorts per transaction
        # Transaction: CSR_in_agent_xaction
        self._xports['CSR_in_agent_xaction'] = xsp.XPort()
        self._xpins['io_csr_intrBitSet'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_csr_intrBitSet'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_csr_intrBitSet", self._xpins['io_csr_intrBitSet'].xdata)
        self._xpins['io_csr_wfiEvent'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_csr_wfiEvent'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_csr_wfiEvent", self._xpins['io_csr_wfiEvent'].xdata)
        self._xpins['io_csr_criticalErrorState'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_csr_criticalErrorState'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_csr_criticalErrorState", self._xpins['io_csr_criticalErrorState'].xdata)
        self._xpins['io_snpt_snptDeq'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_snpt_snptDeq'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_snpt_snptDeq", self._xpins['io_snpt_snptDeq'].xdata)
        self._xpins['io_snpt_useSnpt'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_snpt_useSnpt'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_snpt_useSnpt", self._xpins['io_snpt_useSnpt'].xdata)
        self._xpins['io_snpt_snptSelect'] = xsp.XPin(xsp.XData(2), self._event)
        self._xpins['io_snpt_snptSelect'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_snpt_snptSelect", self._xpins['io_snpt_snptSelect'].xdata)
        self._xpins['io_snpt_flushVec_0'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_snpt_flushVec_0'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_snpt_flushVec_0", self._xpins['io_snpt_flushVec_0'].xdata)
        self._xpins['io_snpt_flushVec_1'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_snpt_flushVec_1'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_snpt_flushVec_1", self._xpins['io_snpt_flushVec_1'].xdata)
        self._xpins['io_snpt_flushVec_2'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_snpt_flushVec_2'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_snpt_flushVec_2", self._xpins['io_snpt_flushVec_2'].xdata)
        self._xpins['io_snpt_flushVec_3'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_snpt_flushVec_3'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_snpt_flushVec_3", self._xpins['io_snpt_flushVec_3'].xdata)
        self._xpins['io_wfi_safeFromMem'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_wfi_safeFromMem'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_wfi_safeFromMem", self._xpins['io_wfi_safeFromMem'].xdata)
        self._xpins['io_wfi_safeFromFrontend'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_wfi_safeFromFrontend'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_wfi_safeFromFrontend", self._xpins['io_wfi_safeFromFrontend'].xdata)
        self._xpins['io_wfi_enable'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_wfi_enable'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_wfi_enable", self._xpins['io_wfi_enable'].xdata)
        self._xpins['io_fromVecExcpMod_busy'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_fromVecExcpMod_busy'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_fromVecExcpMod_busy", self._xpins['io_fromVecExcpMod_busy'].xdata)
        self._xpins['io_readGPAMemData_gpaddr'] = xsp.XPin(xsp.XData(56), self._event)
        self._xpins['io_readGPAMemData_gpaddr'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_readGPAMemData_gpaddr", self._xpins['io_readGPAMemData_gpaddr'].xdata)
        self._xpins['io_readGPAMemData_isForVSnonLeafPTE'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_readGPAMemData_isForVSnonLeafPTE'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_readGPAMemData_isForVSnonLeafPTE", self._xpins['io_readGPAMemData_isForVSnonLeafPTE'].xdata)
        self._xpins['io_vstartIsZero'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_vstartIsZero'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_vstartIsZero", self._xpins['io_vstartIsZero'].xdata)
        self._xpins['io_debugEnqLsq_canAccept'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugEnqLsq_canAccept'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_canAccept", self._xpins['io_debugEnqLsq_canAccept'].xdata)
        self._xpins['io_debugEnqLsq_needAlloc_0'] = xsp.XPin(xsp.XData(2), self._event)
        self._xpins['io_debugEnqLsq_needAlloc_0'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_needAlloc_0", self._xpins['io_debugEnqLsq_needAlloc_0'].xdata)
        self._xpins['io_debugEnqLsq_needAlloc_1'] = xsp.XPin(xsp.XData(2), self._event)
        self._xpins['io_debugEnqLsq_needAlloc_1'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_needAlloc_1", self._xpins['io_debugEnqLsq_needAlloc_1'].xdata)
        self._xpins['io_debugEnqLsq_needAlloc_2'] = xsp.XPin(xsp.XData(2), self._event)
        self._xpins['io_debugEnqLsq_needAlloc_2'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_needAlloc_2", self._xpins['io_debugEnqLsq_needAlloc_2'].xdata)
        self._xpins['io_debugEnqLsq_needAlloc_3'] = xsp.XPin(xsp.XData(2), self._event)
        self._xpins['io_debugEnqLsq_needAlloc_3'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_needAlloc_3", self._xpins['io_debugEnqLsq_needAlloc_3'].xdata)
        self._xpins['io_debugEnqLsq_needAlloc_4'] = xsp.XPin(xsp.XData(2), self._event)
        self._xpins['io_debugEnqLsq_needAlloc_4'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_needAlloc_4", self._xpins['io_debugEnqLsq_needAlloc_4'].xdata)
        self._xpins['io_debugEnqLsq_needAlloc_5'] = xsp.XPin(xsp.XData(2), self._event)
        self._xpins['io_debugEnqLsq_needAlloc_5'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_needAlloc_5", self._xpins['io_debugEnqLsq_needAlloc_5'].xdata)
        self._xpins['io_debugEnqLsq_req_0_valid'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugEnqLsq_req_0_valid'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_0_valid", self._xpins['io_debugEnqLsq_req_0_valid'].xdata)
        self._xpins['io_debugEnqLsq_req_0_bits_robIdx_value'] = xsp.XPin(xsp.XData(8), self._event)
        self._xpins['io_debugEnqLsq_req_0_bits_robIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_0_bits_robIdx_value", self._xpins['io_debugEnqLsq_req_0_bits_robIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_0_bits_lqIdx_value'] = xsp.XPin(xsp.XData(7), self._event)
        self._xpins['io_debugEnqLsq_req_0_bits_lqIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_0_bits_lqIdx_value", self._xpins['io_debugEnqLsq_req_0_bits_lqIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_1_valid'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugEnqLsq_req_1_valid'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_1_valid", self._xpins['io_debugEnqLsq_req_1_valid'].xdata)
        self._xpins['io_debugEnqLsq_req_1_bits_robIdx_value'] = xsp.XPin(xsp.XData(8), self._event)
        self._xpins['io_debugEnqLsq_req_1_bits_robIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_1_bits_robIdx_value", self._xpins['io_debugEnqLsq_req_1_bits_robIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_1_bits_lqIdx_value'] = xsp.XPin(xsp.XData(7), self._event)
        self._xpins['io_debugEnqLsq_req_1_bits_lqIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_1_bits_lqIdx_value", self._xpins['io_debugEnqLsq_req_1_bits_lqIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_2_valid'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugEnqLsq_req_2_valid'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_2_valid", self._xpins['io_debugEnqLsq_req_2_valid'].xdata)
        self._xpins['io_debugEnqLsq_req_2_bits_robIdx_value'] = xsp.XPin(xsp.XData(8), self._event)
        self._xpins['io_debugEnqLsq_req_2_bits_robIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_2_bits_robIdx_value", self._xpins['io_debugEnqLsq_req_2_bits_robIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_2_bits_lqIdx_value'] = xsp.XPin(xsp.XData(7), self._event)
        self._xpins['io_debugEnqLsq_req_2_bits_lqIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_2_bits_lqIdx_value", self._xpins['io_debugEnqLsq_req_2_bits_lqIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_3_valid'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugEnqLsq_req_3_valid'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_3_valid", self._xpins['io_debugEnqLsq_req_3_valid'].xdata)
        self._xpins['io_debugEnqLsq_req_3_bits_robIdx_value'] = xsp.XPin(xsp.XData(8), self._event)
        self._xpins['io_debugEnqLsq_req_3_bits_robIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_3_bits_robIdx_value", self._xpins['io_debugEnqLsq_req_3_bits_robIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_3_bits_lqIdx_value'] = xsp.XPin(xsp.XData(7), self._event)
        self._xpins['io_debugEnqLsq_req_3_bits_lqIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_3_bits_lqIdx_value", self._xpins['io_debugEnqLsq_req_3_bits_lqIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_4_valid'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugEnqLsq_req_4_valid'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_4_valid", self._xpins['io_debugEnqLsq_req_4_valid'].xdata)
        self._xpins['io_debugEnqLsq_req_4_bits_robIdx_value'] = xsp.XPin(xsp.XData(8), self._event)
        self._xpins['io_debugEnqLsq_req_4_bits_robIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_4_bits_robIdx_value", self._xpins['io_debugEnqLsq_req_4_bits_robIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_4_bits_lqIdx_value'] = xsp.XPin(xsp.XData(7), self._event)
        self._xpins['io_debugEnqLsq_req_4_bits_lqIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_4_bits_lqIdx_value", self._xpins['io_debugEnqLsq_req_4_bits_lqIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_5_valid'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugEnqLsq_req_5_valid'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_5_valid", self._xpins['io_debugEnqLsq_req_5_valid'].xdata)
        self._xpins['io_debugEnqLsq_req_5_bits_robIdx_value'] = xsp.XPin(xsp.XData(8), self._event)
        self._xpins['io_debugEnqLsq_req_5_bits_robIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_5_bits_robIdx_value", self._xpins['io_debugEnqLsq_req_5_bits_robIdx_value'].xdata)
        self._xpins['io_debugEnqLsq_req_5_bits_lqIdx_value'] = xsp.XPin(xsp.XData(7), self._event)
        self._xpins['io_debugEnqLsq_req_5_bits_lqIdx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugEnqLsq_req_5_bits_lqIdx_value", self._xpins['io_debugEnqLsq_req_5_bits_lqIdx_value'].xdata)
        self._xpins['io_debugInstrAddrTransType_bare'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugInstrAddrTransType_bare'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugInstrAddrTransType_bare", self._xpins['io_debugInstrAddrTransType_bare'].xdata)
        self._xpins['io_debugInstrAddrTransType_sv39'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugInstrAddrTransType_sv39'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugInstrAddrTransType_sv39", self._xpins['io_debugInstrAddrTransType_sv39'].xdata)
        self._xpins['io_debugInstrAddrTransType_sv39x4'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugInstrAddrTransType_sv39x4'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugInstrAddrTransType_sv39x4", self._xpins['io_debugInstrAddrTransType_sv39x4'].xdata)
        self._xpins['io_debugInstrAddrTransType_sv48'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugInstrAddrTransType_sv48'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugInstrAddrTransType_sv48", self._xpins['io_debugInstrAddrTransType_sv48'].xdata)
        self._xpins['io_debugInstrAddrTransType_sv48x4'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['io_debugInstrAddrTransType_sv48x4'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_debugInstrAddrTransType_sv48x4", self._xpins['io_debugInstrAddrTransType_sv48x4'].xdata)
        self._xpins['io_storeDebugInfo_0_robidx_value'] = xsp.XPin(xsp.XData(8), self._event)
        self._xpins['io_storeDebugInfo_0_robidx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_storeDebugInfo_0_robidx_value", self._xpins['io_storeDebugInfo_0_robidx_value'].xdata)
        self._xpins['io_storeDebugInfo_1_robidx_value'] = xsp.XPin(xsp.XData(8), self._event)
        self._xpins['io_storeDebugInfo_1_robidx_value'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("io_storeDebugInfo_1_robidx_value", self._xpins['io_storeDebugInfo_1_robidx_value'].xdata)
        self._xpins['compare'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['compare'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("compare", self._xpins['compare'].xdata)
        self._xpins['CSR_in_agent_xaction'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['CSR_in_agent_xaction'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("CSR_in_agent_xaction", self._xpins['CSR_in_agent_xaction'].xdata)
        self._xpins['super_result'] = xsp.XPin(xsp.XData(1), self._event)
        self._xpins['super_result'].xdata.AsImmWrite()
        self._xports['CSR_in_agent_xaction'].Add("super_result", self._xpins['super_result'].xdata)
        # Create pin accessors
        self.io_csr_intrBitSet = _PinWrapper(self._xpins['io_csr_intrBitSet'])
        self.io_csr_wfiEvent = _PinWrapper(self._xpins['io_csr_wfiEvent'])
        self.io_csr_criticalErrorState = _PinWrapper(self._xpins['io_csr_criticalErrorState'])
        self.io_snpt_snptDeq = _PinWrapper(self._xpins['io_snpt_snptDeq'])
        self.io_snpt_useSnpt = _PinWrapper(self._xpins['io_snpt_useSnpt'])
        self.io_snpt_snptSelect = _PinWrapper(self._xpins['io_snpt_snptSelect'])
        self.io_snpt_flushVec_0 = _PinWrapper(self._xpins['io_snpt_flushVec_0'])
        self.io_snpt_flushVec_1 = _PinWrapper(self._xpins['io_snpt_flushVec_1'])
        self.io_snpt_flushVec_2 = _PinWrapper(self._xpins['io_snpt_flushVec_2'])
        self.io_snpt_flushVec_3 = _PinWrapper(self._xpins['io_snpt_flushVec_3'])
        self.io_wfi_safeFromMem = _PinWrapper(self._xpins['io_wfi_safeFromMem'])
        self.io_wfi_safeFromFrontend = _PinWrapper(self._xpins['io_wfi_safeFromFrontend'])
        self.io_wfi_enable = _PinWrapper(self._xpins['io_wfi_enable'])
        self.io_fromVecExcpMod_busy = _PinWrapper(self._xpins['io_fromVecExcpMod_busy'])
        self.io_readGPAMemData_gpaddr = _PinWrapper(self._xpins['io_readGPAMemData_gpaddr'])
        self.io_readGPAMemData_isForVSnonLeafPTE = _PinWrapper(self._xpins['io_readGPAMemData_isForVSnonLeafPTE'])
        self.io_vstartIsZero = _PinWrapper(self._xpins['io_vstartIsZero'])
        self.io_debugEnqLsq_canAccept = _PinWrapper(self._xpins['io_debugEnqLsq_canAccept'])
        self.io_debugEnqLsq_needAlloc_0 = _PinWrapper(self._xpins['io_debugEnqLsq_needAlloc_0'])
        self.io_debugEnqLsq_needAlloc_1 = _PinWrapper(self._xpins['io_debugEnqLsq_needAlloc_1'])
        self.io_debugEnqLsq_needAlloc_2 = _PinWrapper(self._xpins['io_debugEnqLsq_needAlloc_2'])
        self.io_debugEnqLsq_needAlloc_3 = _PinWrapper(self._xpins['io_debugEnqLsq_needAlloc_3'])
        self.io_debugEnqLsq_needAlloc_4 = _PinWrapper(self._xpins['io_debugEnqLsq_needAlloc_4'])
        self.io_debugEnqLsq_needAlloc_5 = _PinWrapper(self._xpins['io_debugEnqLsq_needAlloc_5'])
        self.io_debugEnqLsq_req_0_valid = _PinWrapper(self._xpins['io_debugEnqLsq_req_0_valid'])
        self.io_debugEnqLsq_req_0_bits_robIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_0_bits_robIdx_value'])
        self.io_debugEnqLsq_req_0_bits_lqIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_0_bits_lqIdx_value'])
        self.io_debugEnqLsq_req_1_valid = _PinWrapper(self._xpins['io_debugEnqLsq_req_1_valid'])
        self.io_debugEnqLsq_req_1_bits_robIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_1_bits_robIdx_value'])
        self.io_debugEnqLsq_req_1_bits_lqIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_1_bits_lqIdx_value'])
        self.io_debugEnqLsq_req_2_valid = _PinWrapper(self._xpins['io_debugEnqLsq_req_2_valid'])
        self.io_debugEnqLsq_req_2_bits_robIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_2_bits_robIdx_value'])
        self.io_debugEnqLsq_req_2_bits_lqIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_2_bits_lqIdx_value'])
        self.io_debugEnqLsq_req_3_valid = _PinWrapper(self._xpins['io_debugEnqLsq_req_3_valid'])
        self.io_debugEnqLsq_req_3_bits_robIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_3_bits_robIdx_value'])
        self.io_debugEnqLsq_req_3_bits_lqIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_3_bits_lqIdx_value'])
        self.io_debugEnqLsq_req_4_valid = _PinWrapper(self._xpins['io_debugEnqLsq_req_4_valid'])
        self.io_debugEnqLsq_req_4_bits_robIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_4_bits_robIdx_value'])
        self.io_debugEnqLsq_req_4_bits_lqIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_4_bits_lqIdx_value'])
        self.io_debugEnqLsq_req_5_valid = _PinWrapper(self._xpins['io_debugEnqLsq_req_5_valid'])
        self.io_debugEnqLsq_req_5_bits_robIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_5_bits_robIdx_value'])
        self.io_debugEnqLsq_req_5_bits_lqIdx_value = _PinWrapper(self._xpins['io_debugEnqLsq_req_5_bits_lqIdx_value'])
        self.io_debugInstrAddrTransType_bare = _PinWrapper(self._xpins['io_debugInstrAddrTransType_bare'])
        self.io_debugInstrAddrTransType_sv39 = _PinWrapper(self._xpins['io_debugInstrAddrTransType_sv39'])
        self.io_debugInstrAddrTransType_sv39x4 = _PinWrapper(self._xpins['io_debugInstrAddrTransType_sv39x4'])
        self.io_debugInstrAddrTransType_sv48 = _PinWrapper(self._xpins['io_debugInstrAddrTransType_sv48'])
        self.io_debugInstrAddrTransType_sv48x4 = _PinWrapper(self._xpins['io_debugInstrAddrTransType_sv48x4'])
        self.io_storeDebugInfo_0_robidx_value = _PinWrapper(self._xpins['io_storeDebugInfo_0_robidx_value'])
        self.io_storeDebugInfo_1_robidx_value = _PinWrapper(self._xpins['io_storeDebugInfo_1_robidx_value'])
        self.compare = _PinWrapper(self._xpins['compare'])
        self.CSR_in_agent_xaction = _PinWrapper(self._xpins['CSR_in_agent_xaction'])
        self.super_result = _PinWrapper(self._xpins['super_result'])
        # Monitor callback
        def _monitor_callback(trans_type: str, trans_obj):
            """Internal callback for monitor updates."""
            try:
                # Update pins from received transaction
                
                if trans_type == 'CSR_in_agent_xaction':   
                    self._xpins['io_csr_intrBitSet'].xdata.value = trans_obj.io_csr_intrBitSet.value
                    self._xpins['io_csr_wfiEvent'].xdata.value = trans_obj.io_csr_wfiEvent.value
                    self._xpins['io_csr_criticalErrorState'].xdata.value = trans_obj.io_csr_criticalErrorState.value
                    self._xpins['io_snpt_snptDeq'].xdata.value = trans_obj.io_snpt_snptDeq.value
                    self._xpins['io_snpt_useSnpt'].xdata.value = trans_obj.io_snpt_useSnpt.value
                    self._xpins['io_snpt_snptSelect'].xdata.value = trans_obj.io_snpt_snptSelect.value
                    self._xpins['io_snpt_flushVec_0'].xdata.value = trans_obj.io_snpt_flushVec_0.value
                    self._xpins['io_snpt_flushVec_1'].xdata.value = trans_obj.io_snpt_flushVec_1.value
                    self._xpins['io_snpt_flushVec_2'].xdata.value = trans_obj.io_snpt_flushVec_2.value
                    self._xpins['io_snpt_flushVec_3'].xdata.value = trans_obj.io_snpt_flushVec_3.value
                    self._xpins['io_wfi_safeFromMem'].xdata.value = trans_obj.io_wfi_safeFromMem.value
                    self._xpins['io_wfi_safeFromFrontend'].xdata.value = trans_obj.io_wfi_safeFromFrontend.value
                    self._xpins['io_wfi_enable'].xdata.value = trans_obj.io_wfi_enable.value
                    self._xpins['io_fromVecExcpMod_busy'].xdata.value = trans_obj.io_fromVecExcpMod_busy.value
                    self._xpins['io_readGPAMemData_gpaddr'].xdata.value = trans_obj.io_readGPAMemData_gpaddr.value
                    self._xpins['io_readGPAMemData_isForVSnonLeafPTE'].xdata.value = trans_obj.io_readGPAMemData_isForVSnonLeafPTE.value
                    self._xpins['io_vstartIsZero'].xdata.value = trans_obj.io_vstartIsZero.value
                    self._xpins['io_debugEnqLsq_canAccept'].xdata.value = trans_obj.io_debugEnqLsq_canAccept.value
                    self._xpins['io_debugEnqLsq_needAlloc_0'].xdata.value = trans_obj.io_debugEnqLsq_needAlloc_0.value
                    self._xpins['io_debugEnqLsq_needAlloc_1'].xdata.value = trans_obj.io_debugEnqLsq_needAlloc_1.value
                    self._xpins['io_debugEnqLsq_needAlloc_2'].xdata.value = trans_obj.io_debugEnqLsq_needAlloc_2.value
                    self._xpins['io_debugEnqLsq_needAlloc_3'].xdata.value = trans_obj.io_debugEnqLsq_needAlloc_3.value
                    self._xpins['io_debugEnqLsq_needAlloc_4'].xdata.value = trans_obj.io_debugEnqLsq_needAlloc_4.value
                    self._xpins['io_debugEnqLsq_needAlloc_5'].xdata.value = trans_obj.io_debugEnqLsq_needAlloc_5.value
                    self._xpins['io_debugEnqLsq_req_0_valid'].xdata.value = trans_obj.io_debugEnqLsq_req_0_valid.value
                    self._xpins['io_debugEnqLsq_req_0_bits_robIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_0_bits_robIdx_value.value
                    self._xpins['io_debugEnqLsq_req_0_bits_lqIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_0_bits_lqIdx_value.value
                    self._xpins['io_debugEnqLsq_req_1_valid'].xdata.value = trans_obj.io_debugEnqLsq_req_1_valid.value
                    self._xpins['io_debugEnqLsq_req_1_bits_robIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_1_bits_robIdx_value.value
                    self._xpins['io_debugEnqLsq_req_1_bits_lqIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_1_bits_lqIdx_value.value
                    self._xpins['io_debugEnqLsq_req_2_valid'].xdata.value = trans_obj.io_debugEnqLsq_req_2_valid.value
                    self._xpins['io_debugEnqLsq_req_2_bits_robIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_2_bits_robIdx_value.value
                    self._xpins['io_debugEnqLsq_req_2_bits_lqIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_2_bits_lqIdx_value.value
                    self._xpins['io_debugEnqLsq_req_3_valid'].xdata.value = trans_obj.io_debugEnqLsq_req_3_valid.value
                    self._xpins['io_debugEnqLsq_req_3_bits_robIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_3_bits_robIdx_value.value
                    self._xpins['io_debugEnqLsq_req_3_bits_lqIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_3_bits_lqIdx_value.value
                    self._xpins['io_debugEnqLsq_req_4_valid'].xdata.value = trans_obj.io_debugEnqLsq_req_4_valid.value
                    self._xpins['io_debugEnqLsq_req_4_bits_robIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_4_bits_robIdx_value.value
                    self._xpins['io_debugEnqLsq_req_4_bits_lqIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_4_bits_lqIdx_value.value
                    self._xpins['io_debugEnqLsq_req_5_valid'].xdata.value = trans_obj.io_debugEnqLsq_req_5_valid.value
                    self._xpins['io_debugEnqLsq_req_5_bits_robIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_5_bits_robIdx_value.value
                    self._xpins['io_debugEnqLsq_req_5_bits_lqIdx_value'].xdata.value = trans_obj.io_debugEnqLsq_req_5_bits_lqIdx_value.value
                    self._xpins['io_debugInstrAddrTransType_bare'].xdata.value = trans_obj.io_debugInstrAddrTransType_bare.value
                    self._xpins['io_debugInstrAddrTransType_sv39'].xdata.value = trans_obj.io_debugInstrAddrTransType_sv39.value
                    self._xpins['io_debugInstrAddrTransType_sv39x4'].xdata.value = trans_obj.io_debugInstrAddrTransType_sv39x4.value
                    self._xpins['io_debugInstrAddrTransType_sv48'].xdata.value = trans_obj.io_debugInstrAddrTransType_sv48.value
                    self._xpins['io_debugInstrAddrTransType_sv48x4'].xdata.value = trans_obj.io_debugInstrAddrTransType_sv48x4.value
                    self._xpins['io_storeDebugInfo_0_robidx_value'].xdata.value = trans_obj.io_storeDebugInfo_0_robidx_value.value
                    self._xpins['io_storeDebugInfo_1_robidx_value'].xdata.value = trans_obj.io_storeDebugInfo_1_robidx_value.value
                    self._xpins['compare'].xdata.value = trans_obj.compare.value
                    self._xpins['CSR_in_agent_xaction'].xdata.value = trans_obj.CSR_in_agent_xaction.value
                    self._xpins['super_result'].xdata.value = trans_obj.super_result.value
                    
                self._callback_pending = True
            except Exception as e:
                print(f"Monitor callback error: {e}")

        # Initialize unified Agent (disable auto_register, we'll register manually)
        self.agent = Agent(monitor_callback=_monitor_callback, auto_register=False)

        # Register all transaction types
        send_port = kwargs.get('send_port_CSR_in_agent_xaction', 'CSR_in_agent_xaction')
        receive_port = kwargs.get('receive_port_CSR_in_agent_xaction', 'CSR_in_agent_xaction')
        self.agent.register_transaction(CSR_in_agent_xaction, send_port=send_port, receive_port=receive_port)
        
        self.dut = self

        class _Clock:
            def __init__(self, agent): self.agent = agent
            @property
            def clk(self): return self.agent._cycle_count
        self.xclock = _Clock(self.agent)

    def Step(self, cycles: int = 1):
        """
        Advance simulation by specified cycles.
        1. Send current pin values as transactions
        2. Run simulation
        3. Update pins from monitor
        4. Execute clock callbacks (after monitor update)
        """
        for i in range(cycles):
            # Create and drive transactions
            tr = CSR_in_agent_xaction()
            tr.io_csr_intrBitSet.value = self._xpins['io_csr_intrBitSet'].xdata.value
            tr.io_csr_wfiEvent.value = self._xpins['io_csr_wfiEvent'].xdata.value
            tr.io_csr_criticalErrorState.value = self._xpins['io_csr_criticalErrorState'].xdata.value
            tr.io_snpt_snptDeq.value = self._xpins['io_snpt_snptDeq'].xdata.value
            tr.io_snpt_useSnpt.value = self._xpins['io_snpt_useSnpt'].xdata.value
            tr.io_snpt_snptSelect.value = self._xpins['io_snpt_snptSelect'].xdata.value
            tr.io_snpt_flushVec_0.value = self._xpins['io_snpt_flushVec_0'].xdata.value
            tr.io_snpt_flushVec_1.value = self._xpins['io_snpt_flushVec_1'].xdata.value
            tr.io_snpt_flushVec_2.value = self._xpins['io_snpt_flushVec_2'].xdata.value
            tr.io_snpt_flushVec_3.value = self._xpins['io_snpt_flushVec_3'].xdata.value
            tr.io_wfi_safeFromMem.value = self._xpins['io_wfi_safeFromMem'].xdata.value
            tr.io_wfi_safeFromFrontend.value = self._xpins['io_wfi_safeFromFrontend'].xdata.value
            tr.io_wfi_enable.value = self._xpins['io_wfi_enable'].xdata.value
            tr.io_fromVecExcpMod_busy.value = self._xpins['io_fromVecExcpMod_busy'].xdata.value
            tr.io_readGPAMemData_gpaddr.value = self._xpins['io_readGPAMemData_gpaddr'].xdata.value
            tr.io_readGPAMemData_isForVSnonLeafPTE.value = self._xpins['io_readGPAMemData_isForVSnonLeafPTE'].xdata.value
            tr.io_vstartIsZero.value = self._xpins['io_vstartIsZero'].xdata.value
            tr.io_debugEnqLsq_canAccept.value = self._xpins['io_debugEnqLsq_canAccept'].xdata.value
            tr.io_debugEnqLsq_needAlloc_0.value = self._xpins['io_debugEnqLsq_needAlloc_0'].xdata.value
            tr.io_debugEnqLsq_needAlloc_1.value = self._xpins['io_debugEnqLsq_needAlloc_1'].xdata.value
            tr.io_debugEnqLsq_needAlloc_2.value = self._xpins['io_debugEnqLsq_needAlloc_2'].xdata.value
            tr.io_debugEnqLsq_needAlloc_3.value = self._xpins['io_debugEnqLsq_needAlloc_3'].xdata.value
            tr.io_debugEnqLsq_needAlloc_4.value = self._xpins['io_debugEnqLsq_needAlloc_4'].xdata.value
            tr.io_debugEnqLsq_needAlloc_5.value = self._xpins['io_debugEnqLsq_needAlloc_5'].xdata.value
            tr.io_debugEnqLsq_req_0_valid.value = self._xpins['io_debugEnqLsq_req_0_valid'].xdata.value
            tr.io_debugEnqLsq_req_0_bits_robIdx_value.value = self._xpins['io_debugEnqLsq_req_0_bits_robIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_0_bits_lqIdx_value.value = self._xpins['io_debugEnqLsq_req_0_bits_lqIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_1_valid.value = self._xpins['io_debugEnqLsq_req_1_valid'].xdata.value
            tr.io_debugEnqLsq_req_1_bits_robIdx_value.value = self._xpins['io_debugEnqLsq_req_1_bits_robIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_1_bits_lqIdx_value.value = self._xpins['io_debugEnqLsq_req_1_bits_lqIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_2_valid.value = self._xpins['io_debugEnqLsq_req_2_valid'].xdata.value
            tr.io_debugEnqLsq_req_2_bits_robIdx_value.value = self._xpins['io_debugEnqLsq_req_2_bits_robIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_2_bits_lqIdx_value.value = self._xpins['io_debugEnqLsq_req_2_bits_lqIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_3_valid.value = self._xpins['io_debugEnqLsq_req_3_valid'].xdata.value
            tr.io_debugEnqLsq_req_3_bits_robIdx_value.value = self._xpins['io_debugEnqLsq_req_3_bits_robIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_3_bits_lqIdx_value.value = self._xpins['io_debugEnqLsq_req_3_bits_lqIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_4_valid.value = self._xpins['io_debugEnqLsq_req_4_valid'].xdata.value
            tr.io_debugEnqLsq_req_4_bits_robIdx_value.value = self._xpins['io_debugEnqLsq_req_4_bits_robIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_4_bits_lqIdx_value.value = self._xpins['io_debugEnqLsq_req_4_bits_lqIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_5_valid.value = self._xpins['io_debugEnqLsq_req_5_valid'].xdata.value
            tr.io_debugEnqLsq_req_5_bits_robIdx_value.value = self._xpins['io_debugEnqLsq_req_5_bits_robIdx_value'].xdata.value
            tr.io_debugEnqLsq_req_5_bits_lqIdx_value.value = self._xpins['io_debugEnqLsq_req_5_bits_lqIdx_value'].xdata.value
            tr.io_debugInstrAddrTransType_bare.value = self._xpins['io_debugInstrAddrTransType_bare'].xdata.value
            tr.io_debugInstrAddrTransType_sv39.value = self._xpins['io_debugInstrAddrTransType_sv39'].xdata.value
            tr.io_debugInstrAddrTransType_sv39x4.value = self._xpins['io_debugInstrAddrTransType_sv39x4'].xdata.value
            tr.io_debugInstrAddrTransType_sv48.value = self._xpins['io_debugInstrAddrTransType_sv48'].xdata.value
            tr.io_debugInstrAddrTransType_sv48x4.value = self._xpins['io_debugInstrAddrTransType_sv48x4'].xdata.value
            tr.io_storeDebugInfo_0_robidx_value.value = self._xpins['io_storeDebugInfo_0_robidx_value'].xdata.value
            tr.io_storeDebugInfo_1_robidx_value.value = self._xpins['io_storeDebugInfo_1_robidx_value'].xdata.value
            tr.compare.value = self._xpins['compare'].xdata.value
            tr.CSR_in_agent_xaction.value = self._xpins['CSR_in_agent_xaction'].xdata.value
            tr.super_result.value = self._xpins['super_result'].xdata.value
            self.agent.drive(tr)
            self._callback_pending = False

            # Run 1 cycle WITHOUT triggering callbacks yet
            self.agent.run(1, count_cycles=False)

            # Run extra cycles for monitor feedback without counting
            self.agent.run(self._monitor_extra_cycles, count_cycles=False)

            # Wait for monitor callback (without counting cycles)
            wait_count = 0
            while not self._callback_pending and wait_count < 10:
                self.agent.run(1, count_cycles=False)
                wait_count += 1

            # Trigger user callback
            if self._callback_pending and self._user_callback:
                self._user_callback(self)
                self._callback_pending = False

            # NOW increment cycle and trigger callbacks after monitor update
            if self.agent._clock_enabled:
                self.agent._cycle_count += 1
                for callback in self.agent._posedge_callbacks:
                    callback(self.agent._cycle_count)

    def SetUpdateCallback(self, callback: Optional[Callable[['DUTCSR_in_agent_xaction'], None]]):
        """Register callback after monitor updates."""
        self._user_callback = callback

    def SetZero(self):
        """Set all pins to zero."""
        self._xpins['io_csr_intrBitSet'].xdata.value = 0
        self._xpins['io_csr_wfiEvent'].xdata.value = 0
        self._xpins['io_csr_criticalErrorState'].xdata.value = 0
        self._xpins['io_snpt_snptDeq'].xdata.value = 0
        self._xpins['io_snpt_useSnpt'].xdata.value = 0
        self._xpins['io_snpt_snptSelect'].xdata.value = 0
        self._xpins['io_snpt_flushVec_0'].xdata.value = 0
        self._xpins['io_snpt_flushVec_1'].xdata.value = 0
        self._xpins['io_snpt_flushVec_2'].xdata.value = 0
        self._xpins['io_snpt_flushVec_3'].xdata.value = 0
        self._xpins['io_wfi_safeFromMem'].xdata.value = 0
        self._xpins['io_wfi_safeFromFrontend'].xdata.value = 0
        self._xpins['io_wfi_enable'].xdata.value = 0
        self._xpins['io_fromVecExcpMod_busy'].xdata.value = 0
        self._xpins['io_readGPAMemData_gpaddr'].xdata.value = 0
        self._xpins['io_readGPAMemData_isForVSnonLeafPTE'].xdata.value = 0
        self._xpins['io_vstartIsZero'].xdata.value = 0
        self._xpins['io_debugEnqLsq_canAccept'].xdata.value = 0
        self._xpins['io_debugEnqLsq_needAlloc_0'].xdata.value = 0
        self._xpins['io_debugEnqLsq_needAlloc_1'].xdata.value = 0
        self._xpins['io_debugEnqLsq_needAlloc_2'].xdata.value = 0
        self._xpins['io_debugEnqLsq_needAlloc_3'].xdata.value = 0
        self._xpins['io_debugEnqLsq_needAlloc_4'].xdata.value = 0
        self._xpins['io_debugEnqLsq_needAlloc_5'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_0_valid'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_0_bits_robIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_0_bits_lqIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_1_valid'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_1_bits_robIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_1_bits_lqIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_2_valid'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_2_bits_robIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_2_bits_lqIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_3_valid'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_3_bits_robIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_3_bits_lqIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_4_valid'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_4_bits_robIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_4_bits_lqIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_5_valid'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_5_bits_robIdx_value'].xdata.value = 0
        self._xpins['io_debugEnqLsq_req_5_bits_lqIdx_value'].xdata.value = 0
        self._xpins['io_debugInstrAddrTransType_bare'].xdata.value = 0
        self._xpins['io_debugInstrAddrTransType_sv39'].xdata.value = 0
        self._xpins['io_debugInstrAddrTransType_sv39x4'].xdata.value = 0
        self._xpins['io_debugInstrAddrTransType_sv48'].xdata.value = 0
        self._xpins['io_debugInstrAddrTransType_sv48x4'].xdata.value = 0
        self._xpins['io_storeDebugInfo_0_robidx_value'].xdata.value = 0
        self._xpins['io_storeDebugInfo_1_robidx_value'].xdata.value = 0
        self._xpins['compare'].xdata.value = 0
        self._xpins['CSR_in_agent_xaction'].xdata.value = 0
        self._xpins['super_result'].xdata.value = 0
        

    def InitClock(self, clock_pin: Optional[str] = None, domain: str = "default", frequency: Optional[float] = None):
        """
        Initialize clock tracking and management.

        Args:
            clock_pin: Name of the clock pin (optional, for validation only)
                      If None, clock tracking works without pin validation
            domain: Clock domain name for documentation (default: "default")
            frequency: Optional clock frequency in Hz

        Example:
            dut.InitClock()  # Simple cycle counting
            dut.InitClock("clk")  # Validate clock pin exists
            dut.InitClock("clk", domain="sys_clk", frequency=100e6)
        """
        if clock_pin is not None and clock_pin not in self._xpins:
            raise ValueError(f"Clock pin '{clock_pin}' not found. Available pins: {list(self._xpins.keys())}")

        # Delegate to Agent
        self.agent.InitClock(domain=domain, frequency=frequency)

    def StepRis(self, callback: Callable[[int], None]):
        """
        Register callback for clock rising edge.

        Args:
            callback: Function that takes cycle number as argument

        Example:
            def on_posedge(cycle):
                print(f"Cycle {cycle}: value = {dut.pin.value}")

            dut.StepRis(on_posedge)
        """
        # Delegate to Agent
        self.agent.StepRis(callback)

    def StepFal(self, callback: Callable[[int], None]):
        """
        Register callback for clock falling edge.

        Args:
            callback: Function that takes cycle number as argument

        Note: Currently falling edge callbacks are not triggered in Pack mode
              as the clock is managed by SystemVerilog testbench.
        """
        # Delegate to Agent
        self.agent.StepFal(callback)

    def GetCycleCount(self) -> int:
        """
        Get current simulation cycle count.

        Returns:
            Number of cycles executed since InitClock

        Example:
            cycle = dut.GetCycleCount()
            print(f"Current cycle: {cycle}")
        """
        # Delegate to Agent
        return self.agent.GetCycleCount()

    def Finish(self):
        """
        Finish simulation and cleanup.

        Example:
            dut.Finish()
        """
        print(f"[Finish] Simulation completed. Total cycles: {self.agent.GetCycleCount()}")

    def GetAgent(self):
        """Get underlying Agent object."""
        return self.agent

    def __repr__(self):
        fields = []
        fields.append(f"io_csr_intrBitSet={self._xpins['io_csr_intrBitSet'].xdata.value}")
        fields.append(f"io_csr_wfiEvent={self._xpins['io_csr_wfiEvent'].xdata.value}")
        fields.append(f"io_csr_criticalErrorState={self._xpins['io_csr_criticalErrorState'].xdata.value}")
        fields.append(f"io_snpt_snptDeq={self._xpins['io_snpt_snptDeq'].xdata.value}")
        fields.append(f"io_snpt_useSnpt={self._xpins['io_snpt_useSnpt'].xdata.value}")
        fields.append(f"io_snpt_snptSelect={self._xpins['io_snpt_snptSelect'].xdata.value}")
        fields.append(f"io_snpt_flushVec_0={self._xpins['io_snpt_flushVec_0'].xdata.value}")
        fields.append(f"io_snpt_flushVec_1={self._xpins['io_snpt_flushVec_1'].xdata.value}")
        fields.append(f"io_snpt_flushVec_2={self._xpins['io_snpt_flushVec_2'].xdata.value}")
        fields.append(f"io_snpt_flushVec_3={self._xpins['io_snpt_flushVec_3'].xdata.value}")
        fields.append(f"io_wfi_safeFromMem={self._xpins['io_wfi_safeFromMem'].xdata.value}")
        fields.append(f"io_wfi_safeFromFrontend={self._xpins['io_wfi_safeFromFrontend'].xdata.value}")
        fields.append(f"io_wfi_enable={self._xpins['io_wfi_enable'].xdata.value}")
        fields.append(f"io_fromVecExcpMod_busy={self._xpins['io_fromVecExcpMod_busy'].xdata.value}")
        fields.append(f"io_readGPAMemData_gpaddr={self._xpins['io_readGPAMemData_gpaddr'].xdata.value}")
        fields.append(f"io_readGPAMemData_isForVSnonLeafPTE={self._xpins['io_readGPAMemData_isForVSnonLeafPTE'].xdata.value}")
        fields.append(f"io_vstartIsZero={self._xpins['io_vstartIsZero'].xdata.value}")
        fields.append(f"io_debugEnqLsq_canAccept={self._xpins['io_debugEnqLsq_canAccept'].xdata.value}")
        fields.append(f"io_debugEnqLsq_needAlloc_0={self._xpins['io_debugEnqLsq_needAlloc_0'].xdata.value}")
        fields.append(f"io_debugEnqLsq_needAlloc_1={self._xpins['io_debugEnqLsq_needAlloc_1'].xdata.value}")
        fields.append(f"io_debugEnqLsq_needAlloc_2={self._xpins['io_debugEnqLsq_needAlloc_2'].xdata.value}")
        fields.append(f"io_debugEnqLsq_needAlloc_3={self._xpins['io_debugEnqLsq_needAlloc_3'].xdata.value}")
        fields.append(f"io_debugEnqLsq_needAlloc_4={self._xpins['io_debugEnqLsq_needAlloc_4'].xdata.value}")
        fields.append(f"io_debugEnqLsq_needAlloc_5={self._xpins['io_debugEnqLsq_needAlloc_5'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_0_valid={self._xpins['io_debugEnqLsq_req_0_valid'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_0_bits_robIdx_value={self._xpins['io_debugEnqLsq_req_0_bits_robIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_0_bits_lqIdx_value={self._xpins['io_debugEnqLsq_req_0_bits_lqIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_1_valid={self._xpins['io_debugEnqLsq_req_1_valid'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_1_bits_robIdx_value={self._xpins['io_debugEnqLsq_req_1_bits_robIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_1_bits_lqIdx_value={self._xpins['io_debugEnqLsq_req_1_bits_lqIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_2_valid={self._xpins['io_debugEnqLsq_req_2_valid'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_2_bits_robIdx_value={self._xpins['io_debugEnqLsq_req_2_bits_robIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_2_bits_lqIdx_value={self._xpins['io_debugEnqLsq_req_2_bits_lqIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_3_valid={self._xpins['io_debugEnqLsq_req_3_valid'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_3_bits_robIdx_value={self._xpins['io_debugEnqLsq_req_3_bits_robIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_3_bits_lqIdx_value={self._xpins['io_debugEnqLsq_req_3_bits_lqIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_4_valid={self._xpins['io_debugEnqLsq_req_4_valid'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_4_bits_robIdx_value={self._xpins['io_debugEnqLsq_req_4_bits_robIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_4_bits_lqIdx_value={self._xpins['io_debugEnqLsq_req_4_bits_lqIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_5_valid={self._xpins['io_debugEnqLsq_req_5_valid'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_5_bits_robIdx_value={self._xpins['io_debugEnqLsq_req_5_bits_robIdx_value'].xdata.value}")
        fields.append(f"io_debugEnqLsq_req_5_bits_lqIdx_value={self._xpins['io_debugEnqLsq_req_5_bits_lqIdx_value'].xdata.value}")
        fields.append(f"io_debugInstrAddrTransType_bare={self._xpins['io_debugInstrAddrTransType_bare'].xdata.value}")
        fields.append(f"io_debugInstrAddrTransType_sv39={self._xpins['io_debugInstrAddrTransType_sv39'].xdata.value}")
        fields.append(f"io_debugInstrAddrTransType_sv39x4={self._xpins['io_debugInstrAddrTransType_sv39x4'].xdata.value}")
        fields.append(f"io_debugInstrAddrTransType_sv48={self._xpins['io_debugInstrAddrTransType_sv48'].xdata.value}")
        fields.append(f"io_debugInstrAddrTransType_sv48x4={self._xpins['io_debugInstrAddrTransType_sv48x4'].xdata.value}")
        fields.append(f"io_storeDebugInfo_0_robidx_value={self._xpins['io_storeDebugInfo_0_robidx_value'].xdata.value}")
        fields.append(f"io_storeDebugInfo_1_robidx_value={self._xpins['io_storeDebugInfo_1_robidx_value'].xdata.value}")
        fields.append(f"compare={self._xpins['compare'].xdata.value}")
        fields.append(f"CSR_in_agent_xaction={self._xpins['CSR_in_agent_xaction'].xdata.value}")
        fields.append(f"super_result={self._xpins['super_result'].xdata.value}")
        if self.agent._clock_enabled:
            fields.append(f"cycle={self.agent.GetCycleCount()}")
        return f"DUTCSR_in_agent_xaction({', '.join(fields)})"

    def RefreshComb(self):
        """Refresh combinational logic (not supported in pack mode)."""
        self.InitClock()
        print("this function is not supported in pack mode")

    def SetWaveform(self, filename: str):
        """Set waveform output file (not supported in pack mode)."""
        print(f"[SetWaveform] Not supported in pack mode. Use VCS +vcdpluson+<filename>")

    def GetWaveFormat(self) -> str:
        """Get waveform file extension (returns empty string in pack mode)."""
        return ""

    def FlushWaveform(self):
        """Flush waveform data to disk (not supported in pack mode)."""
        print("[FlushWaveform] Not supported in pack mode.")

    def SetCoverage(self, filename: str):
        """Set coverage output file (not supported in pack mode)."""
        print(f"[SetCoverage] Not supported in pack mode. Use VCS -cm <metrics>")

    def GetCovMetrics(self) -> int:
        """Get coverage metrics bitmask (returns 0 in pack mode)."""
        return 0

    def ResumeWaveformDump(self):
        """Resume waveform dumping (not supported in pack mode)."""
        print("[ResumeWaveformDump] Not supported in pack mode")
        return 0

    def PauseWaveformDump(self):
        """Pause waveform dumping (not supported in pack mode)."""
        print("[PauseWaveformDump] Not supported in pack mode")
        return 0

    def WaveformPaused(self) -> int:
        """Check if waveform is paused (returns 0 in pack mode)."""
        return 0

    def CheckPoint(self, name: str) -> int:
        """Create simulation checkpoint (not supported in pack mode)."""
        print(f"[CheckPoint] Not supported in pack mode.")
        return 1

    def Restore(self, name: str) -> int:
        """Restore from checkpoint (not supported in pack mode)."""
        print(f"[Restore] Not supported in pack mode.")
        return 1

    def GetInternalSignal(self, name: str, index: int = -1, is_array: bool = False, use_vpi: bool = False):
        """Get internal signal access (not supported in pack mode)."""
        print(f"[GetInternalSignal] Not supported in pack mode.")
        return None

    def GetInternalSignalList(self, prefix: str = "", deep: int = 99, use_vpi: bool = False) -> List[str]:
        """Get internal signal list (not supported in pack mode)."""
        print(f"[GetInternalSignalList] Not supported in pack mode.")
        return []

    def VPIInternalSignalList(self, prefix: str = "", deep: int = 99) -> List[str]:
        """Get internal signal list via VPI (not supported in pack mode)."""
        print(f"[VPIInternalSignalList] Not supported in pack mode.")
        return []

    def GetXPort(self):
        """Get XPort dictionary for all transactions."""
        return self._xports

    def GetXClock(self):
        """Get XClock-like object."""
        return self.xclock


# Public API for DUT mode
__all__ = [
    "Agent",
    "BaseTransaction",
    "DUTCSR_in_agent_xaction",
    "CSR_in_agent_xaction",
    "u",
    "xsp",
]

