# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _tlm_pbsb
else:
    import _tlm_pbsb

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _tlm_pbsb.delete_SwigPyIterator

    def value(self):
        return _tlm_pbsb.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _tlm_pbsb.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _tlm_pbsb.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _tlm_pbsb.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _tlm_pbsb.SwigPyIterator_equal(self, x)

    def copy(self):
        return _tlm_pbsb.SwigPyIterator_copy(self)

    def next(self):
        return _tlm_pbsb.SwigPyIterator_next(self)

    def __next__(self):
        return _tlm_pbsb.SwigPyIterator___next__(self)

    def previous(self):
        return _tlm_pbsb.SwigPyIterator_previous(self)

    def advance(self, n):
        return _tlm_pbsb.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _tlm_pbsb.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _tlm_pbsb.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _tlm_pbsb.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _tlm_pbsb.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _tlm_pbsb.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _tlm_pbsb.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _tlm_pbsb:
_tlm_pbsb.SwigPyIterator_swigregister(SwigPyIterator)
TLM_READ_COMMAND = _tlm_pbsb.TLM_READ_COMMAND
TLM_WRITE_COMMAND = _tlm_pbsb.TLM_WRITE_COMMAND
TLM_IGNORE_COMMAND = _tlm_pbsb.TLM_IGNORE_COMMAND
TLM_OK_RESPONSE = _tlm_pbsb.TLM_OK_RESPONSE
TLM_INCOMPLETE_RESPONSE = _tlm_pbsb.TLM_INCOMPLETE_RESPONSE
TLM_GENERIC_ERROR_RESPONSE = _tlm_pbsb.TLM_GENERIC_ERROR_RESPONSE
TLM_ADDRESS_ERROR_RESPONSE = _tlm_pbsb.TLM_ADDRESS_ERROR_RESPONSE
TLM_COMMAND_ERROR_RESPONSE = _tlm_pbsb.TLM_COMMAND_ERROR_RESPONSE
TLM_BURST_ERROR_RESPONSE = _tlm_pbsb.TLM_BURST_ERROR_RESPONSE
TLM_BYTE_ENABLE_ERROR_RESPONSE = _tlm_pbsb.TLM_BYTE_ENABLE_ERROR_RESPONSE
TLM_MIN_PAYLOAD = _tlm_pbsb.TLM_MIN_PAYLOAD
TLM_FULL_PAYLOAD = _tlm_pbsb.TLM_FULL_PAYLOAD
TLM_FULL_PAYLOAD_ACCEPTED = _tlm_pbsb.TLM_FULL_PAYLOAD_ACCEPTED
class tlm_msg(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cmd = property(_tlm_pbsb.tlm_msg_cmd_get, _tlm_pbsb.tlm_msg_cmd_set)
    resp_status = property(_tlm_pbsb.tlm_msg_resp_status_get, _tlm_pbsb.tlm_msg_resp_status_set)
    option = property(_tlm_pbsb.tlm_msg_option_get, _tlm_pbsb.tlm_msg_option_set)
    delay = property(_tlm_pbsb.tlm_msg_delay_get, _tlm_pbsb.tlm_msg_delay_set)
    time_unit = property(_tlm_pbsb.tlm_msg_time_unit_get, _tlm_pbsb.tlm_msg_time_unit_set)
    data = property(_tlm_pbsb.tlm_msg_data_get, _tlm_pbsb.tlm_msg_data_set)

    def __init__(self, *args):
        _tlm_pbsb.tlm_msg_swiginit(self, _tlm_pbsb.new_tlm_msg(*args))

    def from_bytes(self, data):
        return _tlm_pbsb.tlm_msg_from_bytes(self, data)

    def as_bytes(self):
        return _tlm_pbsb.tlm_msg_as_bytes(self)

    def clone(self):
        return _tlm_pbsb.tlm_msg_clone(self)
    __swig_destroy__ = _tlm_pbsb.delete_tlm_msg

# Register tlm_msg in _tlm_pbsb:
_tlm_pbsb.tlm_msg_swigregister(tlm_msg)

def VcsMain(argc):
    return _tlm_pbsb.VcsMain(argc)

def VcsInit():
    return _tlm_pbsb.VcsInit()

def VcsSimUntil(arg1):
    return _tlm_pbsb.VcsSimUntil(arg1)

def removeSuffix(str, suffix):
    return _tlm_pbsb.removeSuffix(str, suffix)
class TLMSub(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, channel):
        _tlm_pbsb.TLMSub_swiginit(self, _tlm_pbsb.new_TLMSub(channel))
    __swig_destroy__ = _tlm_pbsb.delete_TLMSub

    def MakeChannel(self, channel):
        return _tlm_pbsb.TLMSub_MakeChannel(self, channel)

    def UMakeChannel(self, channel):
        return _tlm_pbsb.TLMSub_UMakeChannel(self, channel)

    def SetHandler(self, handler):
        return _tlm_pbsb.TLMSub_SetHandler(self, handler)

    def Connect(self):
        return _tlm_pbsb.TLMSub_Connect(self)

    def GetChannel(self):
        return _tlm_pbsb.TLMSub_GetChannel(self)

# Register TLMSub in _tlm_pbsb:
_tlm_pbsb.TLMSub_swigregister(TLMSub)
class TLMPub(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, channel):
        _tlm_pbsb.TLMPub_swiginit(self, _tlm_pbsb.new_TLMPub(channel))
    __swig_destroy__ = _tlm_pbsb.delete_TLMPub

    def MakeChannel(self, channel):
        return _tlm_pbsb.TLMPub_MakeChannel(self, channel)

    def UMakeChannel(self, channel):
        return _tlm_pbsb.TLMPub_UMakeChannel(self, channel)

    def SendMsg(self, msg):
        return _tlm_pbsb.TLMPub_SendMsg(self, msg)

    def Connect(self):
        return _tlm_pbsb.TLMPub_Connect(self)

    def GetChannel(self):
        return _tlm_pbsb.TLMPub_GetChannel(self)

# Register TLMPub in _tlm_pbsb:
_tlm_pbsb.TLMPub_swigregister(TLMPub)

def tlm_pbsb_run(*args):
    return _tlm_pbsb.tlm_pbsb_run(*args)

def step(*args):
    return _tlm_pbsb.step(*args)

def tlm_vcs_init(argc):
    return _tlm_pbsb.tlm_vcs_init(argc)

def tlm_vcs_step(delay):
    return _tlm_pbsb.tlm_vcs_step(delay)
class cb_void_tlm_msg(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def set_force_callable(self):
        return _tlm_pbsb.cb_void_tlm_msg_set_force_callable(self)

    def __init__(self):
        if self.__class__ == cb_void_tlm_msg:
            _self = None
        else:
            _self = self
        _tlm_pbsb.cb_void_tlm_msg_swiginit(self, _tlm_pbsb.new_cb_void_tlm_msg(_self, ))
    __swig_destroy__ = _tlm_pbsb.delete_cb_void_tlm_msg

    def call(self, __args1):
        return _tlm_pbsb.cb_void_tlm_msg_call(self, __args1)

    def _xfunction(self, cb):
        return _tlm_pbsb.cb_void_tlm_msg__xfunction(self, cb)

    def __eq__(self, n):
        return _tlm_pbsb.cb_void_tlm_msg___eq__(self, n)

    def __ne__(self, n):
        return _tlm_pbsb.cb_void_tlm_msg___ne__(self, n)
    def __disown__(self):
        self.this.disown()
        _tlm_pbsb.disown_cb_void_tlm_msg(self)
        return weakref.proxy(self)

# Register cb_void_tlm_msg in _tlm_pbsb:
_tlm_pbsb.cb_void_tlm_msg_swigregister(cb_void_tlm_msg)

# -------------------------------------------------------------
# refine callback

def _tlm_sub_handler(fc):
    class Func(cb_void_tlm_msg):
        def __init__(self, func):
            cb_void_tlm_msg.__init__(self)
            self.func = func
            self.set_force_callable()
        def call(self, msg):
            return self.func(msg)
    return Func(fc).__disown__()

TLMSub_old_init__  = TLMSub.__init__
TLMSUB_old_SetHandler = TLMSub.SetHandler

def TLMSub_SetHandler(self, cb):
    return TLMSUB_old_SetHandler(self, _tlm_sub_handler(cb))

def TLMSub__init__(self: TLMSub, ch: str, cb=None):
    ob = TLMSub_old_init__(self, ch)
    if callable(cb):
       TLMSUB_old_SetHandler(self, _tlm_sub_handler(cb))
    return ob

TLMSub.__init__ = TLMSub__init__
TLMSub.SetHandler = TLMSub_SetHandler

old_tlm_vcs_init = tlm_vcs_init
def new_tlm_vcs_init(*args):
    return old_tlm_vcs_init(args)
tlm_vcs_init = new_tlm_vcs_init




